apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hotserver"
  labels:
    app: "hotserver"
spec:
  selector:
    matchLabels:
      app: "hotserver"
  replicas: 1
  template:
    metadata:
      name: "hotserver"
      labels:
        app: "hotserver"
    spec:
      containers:
      - name: "hotserver"
        image: "wesleywillians/esquenta-k8s-live:v2"
        resources:
          requests:
            cpu: "0.01"
            memory: 10Mi
          limits:
            cpu: "0.02"
            memory: 15Mi